spring:
  application:
    name: ai-code-helper

  profiles:
    active: local

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: <Your API KEY>
        model-name: qwen-turbo
      embedding-model:
        model-name: text-embedding-v4
        api-key: <Your API KEY>
bigmodel:
  api-key: <Your API KEY>